apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmf-client-deployment
spec:
  replicas: 1  # Start with 1 replica, adjust for scaling
  selector:
    matchLabels:
      app: cmf-client
  template:
    metadata:
      labels:
        app: cmf-client
    spec:
      containers:
      - name: cmf-client
        image: localhost:5000/cmf-client:latest

