---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cmf-ingress
  namespace: cmf
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: cmf.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cmf-ui
            port:
              number: 3000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: cmf-server
            port:
              number: 8000
      - path: /tensorboard
        pathType: Prefix
        backend:
          service:
            name: tensorboard
            port:
              number: 6006
  - host: neo4j.cmf.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: neo4j
            port:
              number: 7474
  - host: minio.cmf.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 9001
  - host: minio-api.cmf.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 9000
