---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neptune-ingress
  namespace: neptune
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: neptune.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: neptune-server
            port:
              number: 5000
  - host: minio-neptune.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 9001
  - host: minio-api-neptune.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 9000
